name: Build and Release Installer

on:
  push:
    tags:
      - 'v*'  # Déclenche l'action lorsqu'un tag versionné est poussé (ex: v1.0.0)

jobs:
  build:
    runs-on: windows-lastest  # Plus stable que windows-2019 pour le moment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force update GitHub Actions
        run: |
          git config --global --add safe.directory /__w
          gh auth setup-git
          gh extension install actions/runner
          gh actions-runner update
        shell: bash

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Inno Setup Action
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5

      - name: Compile Setup with Inno Setup
        run: iscc /DAppVersion=${{ env.VERSION }} setup.iss
        shell: cmd

      - name: Upload Installer as Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Installer
          path: Output/*.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Output/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
